node_id: "node-2"
listen_host: "127.0.0.1"
listen_port: 9002
peers:
  - { node_id: "node-1", host: "127.0.0.1", port: 9001 }
keys:
  private_key_path: "keys/mesh_shared.key"
  public_key_path: "keys/mesh_shared.pub"


